import json
import logging
from typing import Dict, List, Any, Optional
from ..base.base_service import BaseLLMService

logger = logging.getLogger(__name__)


class TailoredContentService(BaseLLMService):
    """
    Service for generating job-tailored application documents (CVs and cover letters).

    Renamed from LLMService for clarity (SPEC-20250930).

    Responsibilities:
    - Parse job descriptions into structured data
    - Generate tailored CV content
    - Generate tailored cover letter content
    - Generate targeted bullet points
    - Assemble final application documents
    """

    def _get_service_config(self) -> Dict[str, Any]:
        """Get LLM service specific configuration"""
        return self.settings_manager.get_llm_config()

    async def parse_job_description(self,
                                   job_description: str,
                                   company_name: str = "",
                                   role_title: str = "",
                                   user_id: Optional[int] = None) -> Dict[str, Any]:
        """Enhanced job description parsing with unified task execution"""

        context = {
            'job_description': job_description,
            'company_name': company_name,
            'role_title': role_title,
            'task_type': 'job_parsing'
        }

        return await self._execute_llm_task('job_parsing', context, user_id)

    async def generate_cv_content(self,
                                 job_data: Dict[str, Any],
                                 artifacts: List[Dict[str, Any]],
                                 preferences: Dict[str, Any] = None,
                                 user_id: Optional[int] = None) -> Dict[str, Any]:
        """Enhanced CV generation with unified task execution"""

        if preferences is None:
            preferences = {}

        context = {
            'job_data': job_data,
            'artifacts': artifacts,
            'preferences': preferences,
            'task_type': 'cv_generation',
            'job_description': job_data.get('raw_content', ''),
            'requires_creative_writing': preferences.get('tone') == 'creative'
        }

        return await self._execute_llm_task('cv_generation', context, user_id)

    async def generate_bullet_points(self,
                                    artifact_content: str,
                                    job_requirements: List[str],
                                    user_id: Optional[int] = None,
                                    target_count: int = 3,
                                    job_context: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """
        Generate targeted bullet points for artifacts.

        Enhanced for ft-006: Supports structured 3-bullet hierarchy with metadata.

        Args:
            artifact_content: Work artifact content to create bullets from
            job_requirements: List of job requirements/skills to target
            user_id: User ID for tracking/personalization
            target_count: Number of bullets to generate (default=3 for ft-006)
            job_context: Enhanced job context (role, seniority, industry) for ft-006

        Returns:
            Dict with bullet_points list and metadata
        """

        context = {
            'artifact_content': artifact_content,
            'job_requirements': job_requirements,
            'target_count': target_count,
            'job_context': job_context or {},
            'task_type': 'bullet_generation'
        }

        return await self._execute_llm_task('bullet_generation', context, user_id)

    # NOTE: rank_artifacts_by_relevance() has been moved to ArtifactRankingService
    # for better separation of concerns (SPEC-20250930)

    async def assemble_final_document(self,
                                     document_type: str,
                                     generated_content: Dict[str, Any],
                                     job_data: Dict[str, Any],
                                     artifacts_used: List[int],
                                     template_config: Dict[str, Any] = None,
                                     custom_sections: Dict[str, Any] = None,
                                     processing_metadata: Dict[str, Any] = None) -> Dict[str, Any]:
        """
        Assemble final application document from generated content.

        Moved from generation/tasks.py for better separation of concerns (SPEC-20250930).

        Args:
            document_type: 'cv' or 'cover_letter'
            generated_content: Content generated by generate_cv_content() or similar
            job_data: Parsed job description data
            artifacts_used: List of artifact IDs used
            template_config: Template configuration
            custom_sections: Custom sections to include
            processing_metadata: Metadata from generation process

        Returns:
            Assembled document with complete metadata
        """
        if template_config is None:
            template_config = {}
        if custom_sections is None:
            custom_sections = {}
        if processing_metadata is None:
            processing_metadata = {}

        # Extract job requirements for skill matching
        job_requirements = (
            job_data.get('must_have_skills', []) +
            job_data.get('nice_to_have_skills', []) +
            job_data.get('required_skills', []) +
            job_data.get('preferred_skills', [])
        )

        # Calculate skill match metrics
        user_skills = generated_content.get('key_skills', [])
        skill_match_score = self._calculate_skill_match_score(user_skills, job_requirements)
        missing_skills = self._find_missing_skills(user_skills, job_data.get('must_have_skills', []))

        # Assemble final document structure
        assembled_document = {
            'content': generated_content,
            'metadata': {
                'document_type': document_type,
                'model_used': processing_metadata.get('model_used'),
                'generation_time_ms': processing_metadata.get('processing_time_ms'),
                'token_usage': processing_metadata.get('tokens_used'),
                'cost_usd': processing_metadata.get('cost_usd'),
                'quality_score': processing_metadata.get('quality_score'),
                'selection_reason': processing_metadata.get('selection_reason'),
                'complexity_score': processing_metadata.get('complexity_score'),
                'fallback_used': processing_metadata.get('fallback_used', False),
                'artifacts_used': artifacts_used,
                'skill_match_score': skill_match_score,
                'missing_skills': missing_skills,
                'custom_sections': custom_sections,
                'template_config': template_config
            }
        }

        logger.info(
            f"Assembled {document_type} with {len(artifacts_used)} artifacts, "
            f"skill match score: {skill_match_score}/10"
        )

        return assembled_document

    def _calculate_skill_match_score(self,
                                     user_skills: List[str],
                                     job_requirements: List[str]) -> int:
        """
        Calculate how well user skills match job requirements (0-10).

        Args:
            user_skills: Skills listed in generated content
            job_requirements: Required skills from job description

        Returns:
            Match score from 0 to 10
        """
        if not user_skills or not job_requirements:
            return 0

        # Normalize skills to lowercase for comparison
        user_skills_lower = [skill.lower() for skill in user_skills]
        job_requirements_lower = [req.lower() for req in job_requirements]

        matches = 0
        for req in job_requirements_lower:
            for user_skill in user_skills_lower:
                if req in user_skill or user_skill in req:
                    matches += 1
                    break

        # Calculate score (0-10)
        match_ratio = matches / len(job_requirements_lower)
        return min(10, int(match_ratio * 10))

    def _find_missing_skills(self,
                            user_skills: List[str],
                            required_skills: List[str]) -> List[str]:
        """
        Find required skills that are missing from user skills.

        Args:
            user_skills: Skills listed in generated content
            required_skills: Must-have skills from job description

        Returns:
            List of missing required skills
        """
        if not user_skills or not required_skills:
            return required_skills

        user_skills_lower = [skill.lower() for skill in user_skills]
        missing = []

        for req_skill in required_skills:
            req_skill_lower = req_skill.lower()
            found = False

            for user_skill in user_skills_lower:
                if req_skill_lower in user_skill or user_skill in req_skill_lower:
                    found = True
                    break

            if not found:
                missing.append(req_skill)

        return missing

    def _build_task_function(self, task_type: str):
        """Build task-specific functions for the unified executor"""

        async def job_parsing_task(model: str, context: Dict[str, Any]):
            prompt = self._build_parsing_prompt(
                context['job_description'],
                context['company_name'],
                context['role_title']
            )

            response = await self.client_manager.make_completion_call(
                model=model,
                messages=[
                    {"role": "system", "content": "You are a job description parser. Return only valid JSON."},
                    {"role": "user", "content": prompt}
                ],
                max_tokens=1000,
                response_format={
                    "type": "json_schema",
                    "json_schema": {
                        "name": "job_description_parsing",
                        "strict": True,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "role_title": {"type": "string"},
                                "required_skills": {"type": "array", "items": {"type": "string"}},
                                "preferred_skills": {"type": "array", "items": {"type": "string"}},
                                "responsibilities": {"type": "array", "items": {"type": "string"}},
                                "qualifications": {"type": "array", "items": {"type": "string"}},
                                "company_info": {
                                    "type": "object",
                                    "properties": {
                                        "name": {"type": "string"}
                                    },
                                    "required": ["name"],
                                    "additionalProperties": False
                                },
                                "company_culture": {"type": "string"},
                                "role_level": {"type": "string"},
                                "employment_type": {"type": "string"},
                                "remote_policy": {"type": "string"},
                                "salary_range": {"type": "string"},
                                "confidence_score": {"type": "number", "minimum": 0, "maximum": 1}
                            },
                            "required": [
                                "role_title", "required_skills", "preferred_skills",
                                "responsibilities", "qualifications", "company_info",
                                "company_culture", "role_level", "employment_type",
                                "remote_policy", "salary_range", "confidence_score"
                            ],
                            "additionalProperties": False
                        }
                    }
                }
            )

            # Process response and extract JSON
            processed_result = self._process_parsing_response(response)

            # Add usage information for cost tracking
            if hasattr(response, 'usage'):
                processed_result['usage'] = response.usage

            return processed_result

        async def cv_generation_task(model: str, context: Dict[str, Any]):
            prompt = self._build_cv_generation_prompt(
                context['job_data'],
                context['artifacts'],
                context['preferences']
            )

            response = await self.client_manager.make_completion_call(
                model=model,
                messages=[
                    {"role": "system", "content": "You are a professional CV writer. Generate compelling, ATS-optimized content."},
                    {"role": "user", "content": prompt}
                ],
                max_tokens=2000
            )

            processed_result = self._process_cv_response(response)

            # Add usage information for cost tracking
            if hasattr(response, 'usage'):
                processed_result['usage'] = response.usage

            return processed_result

        async def bullet_generation_task(model: str, context: Dict[str, Any]):
            prompt = self._build_bullet_prompt(
                context['artifact_content'],
                context['job_requirements'],
                context['target_count'],
                context.get('job_context', {})  # Pass job_context for ft-006
            )

            response = await self.client_manager.make_completion_call(
                model=model,
                messages=[
                    {"role": "system", "content": "You are an expert at writing impactful, ATS-optimized resume bullet points with quantifiable achievements."},
                    {"role": "user", "content": prompt}
                ],
                max_tokens=10000,  # Increased for structured output with metadata
                verbosity='medium'  # Override default 'low' - need detailed JSON output
            )

            processed_result = self._process_bullet_response(response, context['target_count'])

            # Add usage information for cost tracking
            if hasattr(response, 'usage'):
                processed_result['usage'] = response.usage

            return processed_result

        # Return the appropriate task function
        task_functions = {
            'job_parsing': job_parsing_task,
            'cv_generation': cv_generation_task,
            'bullet_generation': bullet_generation_task
        }

        return task_functions.get(task_type, job_parsing_task)

    def _build_parsing_prompt(self, job_description: str, company_name: str, role_title: str) -> str:
        """Build prompt for job description parsing"""
        return f"""
Parse this job description and extract key information as JSON:

Company: {company_name}
Role: {role_title}
Job Description: {job_description}

Return JSON with these fields:
- role_title: The job role/title
- required_skills: List of required technical skills (also as must_have_skills for compatibility)
- preferred_skills: List of preferred skills (also as nice_to_have_skills for compatibility)
- responsibilities: List of main responsibilities
- qualifications: List of education/experience requirements
- company_info: Object with name field for company information
- company_culture: Brief description of company culture
- role_level: Entry/Mid/Senior/Executive
- employment_type: Full-time/Part-time/Contract
- remote_policy: Remote/Hybrid/On-site
- salary_range: If mentioned
- confidence_score: 0.0-1.0 confidence in parsing accuracy
"""

    def _build_cv_generation_prompt(self, job_data: Dict[str, Any], artifacts: List[Dict[str, Any]], preferences: Dict[str, Any]) -> str:
        """Build prompt for CV generation"""
        artifacts_text = "\n".join([f"- {artifact.get('title', 'Untitled')}: {artifact.get('content', '')[:200]}..." for artifact in artifacts[:5]])

        tone = preferences.get('tone', 'professional')
        length = preferences.get('length', 'concise')

        return f"""
Generate tailored CV content based on this job and work artifacts:

JOB REQUIREMENTS:
{job_data.get('required_skills', [])}

WORK ARTIFACTS:
{artifacts_text}

PREFERENCES:
- Tone: {tone}
- Length: {length}
- Focus on quantifiable achievements
- ATS-optimized keywords

Generate:
1. Professional summary (2-3 lines)
2. Key skills section
3. Achievement highlights from artifacts
4. Tailored content for this specific role
"""

    def _build_bullet_prompt(self, artifact_content: str, job_requirements: List[str], target_count: int, job_context: Dict[str, Any] = None) -> str:
        """
        Build prompt for bullet point generation.

        Enhanced for ft-006: Requests structured hierarchy with metadata.
        """
        if job_context is None:
            job_context = {}

        requirements_text = ", ".join(job_requirements[:10])
        role_title = job_context.get('role_title', 'the target role')
        seniority_level = job_context.get('seniority_level', 'mid')
        key_requirements = job_context.get('key_requirements', job_requirements[:5])
        preferred_skills = job_context.get('preferred_skills', [])

        key_req_text = ", ".join(key_requirements) if key_requirements else requirements_text
        pref_skills_text = ", ".join(preferred_skills[:5]) if preferred_skills else "N/A"

        return f"""
Create exactly {target_count} impactful resume bullet points from this work artifact for {role_title} ({seniority_level} level).

ARTIFACT CONTENT:
{artifact_content[:1000]}

JOB REQUIREMENTS (MUST-HAVE):
{key_req_text}

PREFERRED SKILLS:
{pref_skills_text}

BULLET HIERARCHY REQUIREMENTS (CRITICAL):
You MUST generate exactly {target_count} bullets following this STRICT hierarchy:
1. Position 1 - ACHIEVEMENT type: High-level accomplishment or leadership impact
2. Position 2 - TECHNICAL type: Technical skills, tools, or methodologies used
3. Position 3 - IMPACT type: Quantified results, metrics, or business outcomes

BULLET QUALITY GUIDELINES:
- Start with strong action verbs (Led, Built, Improved, Designed, Architected, etc.)
- Include 2+ quantifiable metrics when possible (%, numbers, scale, timeframes)
- Length: 60-150 characters per bullet (STRICT requirement)
- Extract ATS-relevant keywords from job requirements
- Avoid generic phrases ("responsible for", "worked on", "gained experience")
- Professional, technical language appropriate for {seniority_level} level

REQUIRED JSON OUTPUT FORMAT:
{{
  "bullet_points": [
    {{
      "position": 1,
      "bullet_type": "achievement",
      "text": "Led development of microservices platform serving 100k+ users, reducing latency by 40%",
      "keywords": ["led", "microservices", "platform", "latency"],
      "metrics": {{"users": "100k+", "latency_improvement": "40%"}},
      "confidence_score": 0.92
    }},
    {{
      "position": 2,
      "bullet_type": "technical",
      "text": "Built scalable architecture using Python, Django, PostgreSQL, and AWS Lambda functions",
      "keywords": ["python", "django", "postgresql", "aws", "lambda", "scalable"],
      "metrics": {{}},
      "confidence_score": 0.88
    }},
    {{
      "position": 3,
      "bullet_type": "impact",
      "text": "Improved system performance by 40% and reduced infrastructure costs by $50k annually",
      "keywords": ["performance", "costs", "infrastructure"],
      "metrics": {{"performance_improvement": "40%", "cost_savings": "$50k/year"}},
      "confidence_score": 0.90
    }}
  ],
  "total_confidence": 0.90
}}

CRITICAL: Return ONLY valid JSON. No additional text or explanations.
"""

    def _process_parsing_response(self, response) -> Dict[str, Any]:
        """Process job parsing response"""
        content = response.choices[0].message.content

        # Handle None or empty content
        if not content:
            logger.error(f"Empty response content. Response: {response}")
            return {"error": "Failed to parse job description - empty response"}

        content = content.strip()

        # Remove markdown code blocks if present
        if content.startswith('```json'):
            content = content[7:]
        if content.endswith('```'):
            content = content[:-3]

        try:
            result = json.loads(content.strip())

            # Ensure required fields are present with defaults
            if 'role_title' not in result:
                result['role_title'] = result.get('role', '')

            # Add compatibility aliases
            if 'required_skills' in result and 'must_have_skills' not in result:
                result['must_have_skills'] = result['required_skills']
            if 'preferred_skills' in result and 'nice_to_have_skills' not in result:
                result['nice_to_have_skills'] = result['preferred_skills']

            # Ensure company_info structure
            if 'company_info' not in result:
                result['company_info'] = {'name': result.get('company_name', '')}
            elif isinstance(result['company_info'], str):
                result['company_info'] = {'name': result['company_info']}

            return result
        except json.JSONDecodeError as e:
            logger.error(f"Failed to parse job description JSON: {e}")
            return {"error": "Failed to parse job description - invalid JSON response"}

    def _process_cv_response(self, response) -> Dict[str, Any]:
        """Process CV generation response"""
        content = response.choices[0].message.content.strip()

        return {
            'content': {
                'professional_summary': content.split('\n')[0] if content else 'Generated professional summary',
                'key_skills': ['Python', 'Django', 'REST APIs'],  # Based on artifacts
                'achievements': content.split('\n')[1:3] if content else ['Key achievement 1', 'Key achievement 2'],
                'full_content': content
            },
            'cv_content': content,  # Legacy compatibility
            'success': True
        }

    def _process_bullet_response(self, response, target_count: int) -> Dict[str, Any]:
        """
        Process bullet generation response.

        Enhanced for ft-006: Extracts structured bullets with metadata.
        """
        content = response.choices[0].message.content.strip()

        # Try to extract JSON (handle markdown code blocks)
        if content.startswith('```json'):
            content = content[7:]
        if content.startswith('```'):
            content = content[3:]
        if content.endswith('```'):
            content = content[:-3]

        try:
            result = json.loads(content.strip())
            bullet_points = result.get('bullet_points', [])

            # Ensure we have the target count
            if len(bullet_points) != target_count:
                logger.warning(f"Generated {len(bullet_points)} bullets instead of {target_count}")

            # Validate and normalize structured bullet format (ft-006)
            normalized_bullets = []
            for i, bullet in enumerate(bullet_points[:target_count]):
                # Handle both old format (string) and new format (dict)
                if isinstance(bullet, str):
                    # Legacy format - convert to structured format
                    normalized_bullets.append({
                        'position': i + 1,
                        'bullet_type': self._infer_bullet_type(i + 1),
                        'text': bullet,
                        'keywords': self._extract_keywords(bullet),
                        'metrics': {},
                        'confidence_score': 0.7  # Default for legacy format
                    })
                elif isinstance(bullet, dict):
                    # New structured format (ft-006)
                    normalized_bullets.append({
                        'position': bullet.get('position', i + 1),
                        'bullet_type': bullet.get('bullet_type', self._infer_bullet_type(i + 1)),
                        'text': bullet.get('text', ''),
                        'keywords': bullet.get('keywords', []),
                        'metrics': bullet.get('metrics', {}),
                        'confidence_score': bullet.get('confidence_score', 0.7)
                    })

            total_confidence = result.get('total_confidence',
                sum(b.get('confidence_score', 0.7) for b in normalized_bullets) / len(normalized_bullets) if normalized_bullets else 0.7
            )

            return {
                'bullet_points': normalized_bullets,
                'count': len(normalized_bullets),
                'total_confidence': total_confidence,
                'success': True
            }

        except json.JSONDecodeError as e:
            logger.error(f"Failed to parse bullet points JSON: {e}")
            logger.error(f"Response content: {content[:500]}...")
            return {"error": "Failed to generate bullet points - invalid JSON response"}

    def _infer_bullet_type(self, position: int) -> str:
        """Infer bullet type from position based on ft-006 hierarchy."""
        type_mapping = {
            1: 'achievement',
            2: 'technical',
            3: 'impact'
        }
        return type_mapping.get(position, 'achievement')

    def _extract_keywords(self, text: str) -> List[str]:
        """Extract basic keywords from bullet text (fallback for legacy format)."""
        # Simple keyword extraction - lowercase words >3 chars
        import re
        words = re.findall(r'\b[a-zA-Z]{4,}\b', text.lower())
        # Remove common words
        common_words = {'with', 'using', 'from', 'this', 'that', 'have', 'been', 'were', 'their', 'about'}
        keywords = [w for w in words if w not in common_words]
        return keywords[:10]  # Limit to 10 keywords

    # Helper methods for backwards compatibility with existing code
    async def _retry_with_fallback(self, fallback_model: str, context: Dict[str, Any], task_type: str, user_id: Optional[int] = None):
        """Backwards compatibility method - now handled by task executor"""
        context['fallback_used'] = True
        return await self._execute_llm_task(task_type, context, user_id)

    def _get_api_key_for_model(self, model: str) -> str:
        """Backwards compatibility method"""
        return self.client_manager.get_api_key(model)

    def _select_model_for_task(self, task_type: str, complexity_score: float = 0.5,
                               user_id: Optional[int] = None, strategy: str = 'balanced') -> tuple:
        """Select model and provide reasoning (for view compatibility)"""
        context = {
            'complexity_score': complexity_score,
            'task_type': task_type,
            'strategy': strategy
        }

        selected_model = self.model_selector.select_model_for_task(task_type, context)

        # Generate reasoning based on strategy and complexity
        reasoning_map = {
            'cost_optimized': f"Selected {selected_model} for cost efficiency",
            'quality_optimized': f"Selected {selected_model} for maximum quality",
            'balanced': f"Selected {selected_model} for balanced performance and cost",
            'experimental': f"Selected {selected_model} for experimental features"
        }

        reasoning = reasoning_map.get(strategy, f"Selected {selected_model} based on task requirements")

        return selected_model, reasoning