# Generated by Django 4.2.24 on 2025-10-01 22:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("artifacts", "0005_alter_evidence_options_alter_evidence_artifact_and_more"),
        ("generation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulletGenerationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "job_context",
                    models.JSONField(
                        default=dict,
                        help_text="Job requirements, keywords, and context for bullet generation",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("needs_review", "Needs Review"),
                        ],
                        default="pending",
                        help_text="Current job status",
                        max_length=20,
                    ),
                ),
                (
                    "progress_percentage",
                    models.IntegerField(
                        default=0,
                        help_text="Processing progress (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "generation_attempts",
                    models.IntegerField(
                        default=0, help_text="Number of generation attempts made"
                    ),
                ),
                (
                    "max_attempts",
                    models.IntegerField(
                        default=3,
                        help_text="Maximum generation attempts before marking as failed",
                    ),
                ),
                (
                    "generated_bullets",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Generated bullet points (serialized)",
                    ),
                ),
                (
                    "validation_results",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Validation scores and issues",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if generation failed"
                    ),
                ),
                (
                    "error_traceback",
                    models.TextField(
                        blank=True, help_text="Full traceback for debugging"
                    ),
                ),
                (
                    "processing_duration_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Total processing time in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "llm_cost_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Total LLM API cost for this job",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "tokens_used",
                    models.IntegerField(
                        blank=True, help_text="Total tokens consumed", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "artifact",
                    models.ForeignKey(
                        help_text="Artifact to generate bullets for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bullet_generation_jobs",
                        to="artifacts.artifact",
                    ),
                ),
                (
                    "cv_generation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent CV generation job",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bullet_generation_jobs",
                        to="generation.generateddocument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who requested generation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bullet_generation_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "generation_bullet_generation_job",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BulletPoint",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "position",
                    models.IntegerField(
                        help_text="Position in 3-bullet set (1, 2, or 3)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                (
                    "bullet_type",
                    models.CharField(
                        choices=[
                            ("achievement", "Primary Achievement"),
                            ("technical", "Technical Detail"),
                            ("impact", "Impact/Results"),
                        ],
                        help_text="Structured hierarchy type",
                        max_length=20,
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="Bullet point text (60-150 chars)",
                        max_length=150,
                        validators=[django.core.validators.MinLengthValidator(60)],
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="ATS-relevant keywords extracted from text",
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Quantified metrics (e.g., {"performance_improvement": "40%"})',
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        help_text="LLM confidence in bullet quality (0.0-1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "quality_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Validation quality score (0.0-1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "has_action_verb",
                    models.BooleanField(
                        default=False, help_text="Starts with strong action verb"
                    ),
                ),
                (
                    "keyword_relevance_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Job keyword relevance (0.0-1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "user_approved",
                    models.BooleanField(
                        default=False, help_text="User explicitly approved this bullet"
                    ),
                ),
                (
                    "user_edited",
                    models.BooleanField(
                        default=False, help_text="User manually edited this bullet"
                    ),
                ),
                (
                    "original_text",
                    models.CharField(
                        blank=True,
                        help_text="Original LLM-generated text before user edits",
                        max_length=150,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "artifact",
                    models.ForeignKey(
                        help_text="Artifact this bullet describes",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bullet_points",
                        to="artifacts.artifact",
                    ),
                ),
                (
                    "cv_generation",
                    models.ForeignKey(
                        help_text="CV generation this bullet belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bullet_points",
                        to="generation.generateddocument",
                    ),
                ),
            ],
            options={
                "db_table": "generation_bullet_point",
                "ordering": ["cv_generation", "artifact", "position"],
                "indexes": [
                    models.Index(
                        fields=["cv_generation", "artifact"],
                        name="generation__cv_gene_db42a6_idx",
                    ),
                    models.Index(
                        fields=["user_approved"], name="generation__user_ap_8b41a3_idx"
                    ),
                    models.Index(
                        fields=["quality_score"], name="generation__quality_63b166_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="bulletpoint",
            constraint=models.UniqueConstraint(
                fields=("cv_generation", "artifact", "position"),
                name="unique_bullet_position_per_artifact",
            ),
        ),
        migrations.AddConstraint(
            model_name="bulletpoint",
            constraint=models.CheckConstraint(
                check=models.Q(("position__gte", 1), ("position__lte", 3)),
                name="valid_bullet_position",
            ),
        ),
        migrations.AddIndex(
            model_name="bulletgenerationjob",
            index=models.Index(
                fields=["user", "status"], name="generation__user_id_f76fb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bulletgenerationjob",
            index=models.Index(
                fields=["artifact", "status"], name="generation__artifac_8ecaea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bulletgenerationjob",
            index=models.Index(
                fields=["created_at"], name="generation__created_49e73b_idx"
            ),
        ),
    ]
