# Generated by Django 4.2.24 on 2025-10-01 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("generation", "0002_bulletgenerationjob_bulletpoint_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulletpoint",
            name="cv_generation",
            field=models.ForeignKey(
                blank=True,
                help_text="CV generation this bullet belongs to (optional until associated)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bullet_points",
                to="generation.generateddocument",
            ),
        ),
    ]
