# Generated by Django 4.2.24 on 2025-10-02 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("generation", "0003_alter_bulletpoint_cv_generation"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulletpoint",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when bullet was approved", null=True
            ),
        ),
        migrations.AddField(
            model_name="bulletpoint",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who approved this bullet",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_bullets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="generateddocument",
            name="assembled_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when CV was assembled", null=True
            ),
        ),
        migrations.AddField(
            model_name="generateddocument",
            name="bullets_count",
            field=models.IntegerField(
                default=0, help_text="Total number of bullets generated"
            ),
        ),
        migrations.AddField(
            model_name="generateddocument",
            name="bullets_generated_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when bullets were generated", null=True
            ),
        ),
        migrations.AlterField(
            model_name="generateddocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("bullets_ready", "Bullets Ready"),
                    ("bullets_approved", "Bullets Approved"),
                    ("assembling", "Assembling CV"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="processing",
                max_length=20,
            ),
        ),
    ]
