# Generated by Django 5.2.7 on 2025-10-27 21:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0008_remove_artifact_unified_embedding"),
        ("generation", "0004_bulletpoint_approved_at_bulletpoint_approved_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bulletpoint",
            name="user_rejected",
            field=models.BooleanField(
                default=False, help_text="User explicitly rejected this bullet"
            ),
        ),
        migrations.AddField(
            model_name="generateddocument",
            name="job_description_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Job context data for bullet generation (key_requirements, etc.) - ft-024",
            ),
        ),
        migrations.AddConstraint(
            model_name="bulletpoint",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("user_approved", True), ("user_rejected", True), _negated=True
                ),
                name="user_approved_rejected_mutually_exclusive",
            ),
        ),
    ]
