# Generated by Django 5.2.7 on 2025-10-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("generation", "0005_add_individual_bullet_approval"),
    ]

    operations = [
        migrations.AddField(
            model_name="generateddocument",
            name="last_activity_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Last status/progress update (auto-updates on save)",
            ),
        ),
        migrations.AddField(
            model_name="generateddocument",
            name="started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When generation actually started processing",
                null=True,
            ),
        ),
    ]
