# Generated by Django 5.2.7 on 2025-10-30 08:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("generation", "0006_generateddocument_last_activity_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generateddocument",
            name="last_activity_at",
        ),
        migrations.RemoveField(
            model_name="generateddocument",
            name="started_at",
        ),
    ]
