# Generated by Django 4.2.24 on 2025-10-01 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0004_rename_link_type_to_evidence_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evidence",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Evidence"},
        ),
        migrations.AlterField(
            model_name="evidence",
            name="artifact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence",
                to="artifacts.artifact",
            ),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="evidence_type",
            field=models.CharField(
                choices=[
                    ("github", "GitHub Repository"),
                    ("live_app", "Live Application"),
                    ("document", "Document/PDF"),
                    ("video", "Video File"),
                    ("audio", "Audio File"),
                    ("website", "Website"),
                    ("portfolio", "Portfolio"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
