# Generated by Django 5.2.7 on 2025-10-04 06:19

from django.db import migrations, models


def migrate_deprecated_evidence(apps, schema_editor):
    """
    Handle deprecated evidence types by marking them as inaccessible.
    This allows existing evidence to remain in the database but prevents
    new evidence from using deprecated types.
    """
    Evidence = apps.get_model('artifacts', 'Evidence')

    deprecated_types = ['live_app', 'video', 'audio', 'website', 'portfolio', 'other']
    deprecated_evidence = Evidence.objects.filter(evidence_type__in=deprecated_types)

    count = deprecated_evidence.count()
    if count > 0:
        print(f"\n=== Evidence Type Migration ===")
        print(f"Found {count} evidence record(s) with deprecated types")
        print(f"Marking as inaccessible for manual review...\n")

        # Mark deprecated evidence as inaccessible with migration note
        for evidence in deprecated_evidence:
            # Preserve existing validation_metadata and add migration note
            metadata = evidence.validation_metadata or {}
            metadata['migration_note'] = (
                f"Deprecated evidence type '{evidence.evidence_type}' - requires user review. "
                f"Please update to 'github' or 'document', or remove this evidence."
            )
            evidence.validation_metadata = metadata
            evidence.is_accessible = False
            evidence.save(update_fields=['validation_metadata', 'is_accessible'])

            print(f"  - Artifact ID {evidence.artifact_id}: {evidence.evidence_type} - {evidence.url}")

        print(f"\n{count} evidence record(s) marked for review")
        print("Users will need to review and update their evidence.\n")


def reverse_migration(apps, schema_editor):
    """
    Reverse the migration by clearing the migration note.
    Does not restore deprecated types (would require manual intervention).
    """
    Evidence = apps.get_model('artifacts', 'Evidence')

    # Clear migration notes for evidence that was marked
    evidence_with_notes = Evidence.objects.filter(
        validation_metadata__has_key='migration_note'
    )

    for evidence in evidence_with_notes:
        metadata = evidence.validation_metadata or {}
        if 'migration_note' in metadata:
            del metadata['migration_note']
            evidence.validation_metadata = metadata
            # Optionally restore accessibility (commented out for safety)
            # evidence.is_accessible = True
            evidence.save(update_fields=['validation_metadata'])


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0005_alter_evidence_options_alter_evidence_artifact_and_more"),
    ]

    operations = [
        # First, handle existing deprecated evidence
        migrations.RunPython(
            migrate_deprecated_evidence,
            reverse_code=reverse_migration
        ),
        # Then, update the field choices
        migrations.AlterField(
            model_name="evidence",
            name="evidence_type",
            field=models.CharField(
                choices=[("github", "GitHub Repository"), ("document", "Document/PDF")],
                help_text="Evidence type: github (repository) or document (PDF upload)",
                max_length=20,
            ),
        ),
    ]
