# Generated by Django 5.2.7 on 2025-10-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0006_simplify_evidence_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifact",
            name="user_context",
            field=models.TextField(
                blank=True,
                help_text="User-provided context (immutable, preserved during enrichment)",
            ),
        ),
    ]
