# Generated by Django 5.2.7 on 2025-10-17 23:24
# Modified to use SeparateDatabaseAndState since migration 0012 in llm_services
# already dropped this column using raw SQL.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0007_add_user_context_field"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Database operations: safe SQL that won't fail if column already gone
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE artifacts_artifact DROP COLUMN IF EXISTS unified_embedding CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            # State operations: tell Django the field is removed from the model
            state_operations=[
                migrations.RemoveField(
                    model_name="artifact",
                    name="unified_embedding",
                ),
            ],
        ),
    ]
