# Generated by Django 5.2.7 on 2025-11-07 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0008_remove_artifact_unified_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifact",
            name="last_wizard_step",
            field=models.IntegerField(
                default=1,
                help_text="Last wizard step user reached (1-7) for resume capability",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(7),
                ],
            ),
        ),
        migrations.AddField(
            model_name="artifact",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("processing", "Processing Evidence"),
                    ("review_pending", "Evidence Review Pending"),
                    ("complete", "Complete"),
                    ("abandoned", "Abandoned"),
                ],
                default="draft",
                help_text="Current completion state of artifact in wizard workflow",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="artifact",
            name="wizard_completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when user finalized evidence review (completed wizard)",
                null=True,
            ),
        ),
    ]
