# Generated by Django 5.2.7 on 2025-11-07 19:20

from django.db import migrations


def mark_existing_artifacts_complete(apps, schema_editor):
    """
    Mark all existing artifacts as 'complete' with appropriate metadata.

    Rationale: All artifacts created before this migration were created
    through the old workflow without status tracking. We assume they are
    all complete and usable.
    """
    Artifact = apps.get_model('artifacts', 'Artifact')

    artifacts = Artifact.objects.all()

    for artifact in artifacts:
        artifact.status = 'complete'
        artifact.wizard_completed_at = artifact.created_at  # Best approximation
        artifact.last_wizard_step = 7  # Completed all steps

    # Bulk update for performance
    Artifact.objects.bulk_update(
        artifacts,
        ['status', 'wizard_completed_at', 'last_wizard_step']
    )


def reverse_migration(apps, schema_editor):
    """
    Reverse operation: Set all artifacts back to 'draft'.

    Note: This is primarily for testing. In production, we wouldn't
    want to revert this migration.
    """
    Artifact = apps.get_model('artifacts', 'Artifact')

    Artifact.objects.all().update(
        status='draft',
        wizard_completed_at=None,
        last_wizard_step=1
    )


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0009_add_artifact_status_tracking"),
    ]

    operations = [
        migrations.RunPython(
            mark_existing_artifacts_complete,
            reverse_code=reverse_migration
        ),
    ]
