# Generated by Django 5.2.7 on 2025-11-08 05:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0011_add_reunifying_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="last_wizard_step",
            field=models.IntegerField(
                default=1,
                help_text="Last wizard step user reached (1-8) for resume capability",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(8),
                ],
            ),
        ),
    ]
