# Generated by Django 5.2.7 on 2025-11-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0012_update_wizard_step_max_to_8"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifactprocessingjob",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("phase1_extraction", "Phase 1: Evidence Extraction"),
                    ("phase2_reunification", "Phase 2: Evidence Reunification"),
                ],
                default="phase1_extraction",
                help_text="Type of processing job: Phase 1 (extraction) or Phase 2 (reunification)",
                max_length=30,
            ),
        ),
    ]
