# Generated by Django 5.2.7 on 2025-11-09 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0013_add_job_type_to_processing_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="last_wizard_step",
            field=models.IntegerField(
                default=1,
                help_text="Last wizard step user reached (1-9) for resume capability",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(9),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("processing", "Processing Evidence"),
                    ("review_pending", "Evidence Review Pending"),
                    ("reunifying", "Reunifying Evidence"),
                    ("review_finalized", "Review Finalized"),
                    ("complete", "Complete"),
                    ("abandoned", "Abandoned"),
                ],
                default="draft",
                help_text="Current completion state of artifact in wizard workflow",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="wizard_completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when user accepted artifact (completed wizard at Step 9)",
                null=True,
            ),
        ),
    ]
