# Generated by Django 5.2.7 on 2025-11-09 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0014_add_review_finalized_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="last_wizard_step",
            field=models.IntegerField(
                default=1,
                help_text="Last wizard step user reached (1-6) for resume capability",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(6),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="wizard_completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when user accepted artifact (completed wizard at Step 6)",
                null=True,
            ),
        ),
    ]
