# Generated by Django 5.2.7 on 2025-11-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0015_update_wizard_step_max_to_6"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("processing", "Processing Evidence"),
                    ("review_pending", "Evidence Review Pending"),
                    ("reunifying", "Finalizing Evidence"),
                    ("review_finalized", "Review Finalized"),
                    ("complete", "Complete"),
                    ("abandoned", "Abandoned"),
                ],
                default="draft",
                help_text="Current completion state of artifact in wizard workflow",
                max_length=20,
            ),
        ),
    ]
