# Generated by Django 4.2.24 on 2025-09-25 01:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("llm_services", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="artifactchunk",
            new_name="artifact_ch_artifac_db15f8_idx",
            old_name="artifact_chunk_artifact_idx",
        ),
        migrations.RenameIndex(
            model_name="artifactchunk",
            new_name="artifact_ch_content_503ced_idx",
            old_name="artifact_chunk_hash_idx",
        ),
        migrations.RenameIndex(
            model_name="enhancedartifact",
            new_name="enhanced_ar_user_id_08ae58_idx",
            old_name="enhanced_artifact_user_type_idx",
        ),
        migrations.RenameIndex(
            model_name="enhancedartifact",
            new_name="enhanced_ar_created_863a56_idx",
            old_name="enhanced_artifact_created_idx",
        ),
        migrations.RenameIndex(
            model_name="enhancedartifact",
            new_name="enhanced_ar_embeddi_f97a78_idx",
            old_name="enhanced_artifact_model_idx",
        ),
        migrations.RenameIndex(
            model_name="jobdescriptionembedding",
            new_name="job_embeddi_job_des_147ae2_idx",
            old_name="job_embedding_hash_idx",
        ),
        migrations.RenameIndex(
            model_name="jobdescriptionembedding",
            new_name="job_embeddi_user_id_48c22c_idx",
            old_name="job_embedding_user_accessed_idx",
        ),
        migrations.RenameIndex(
            model_name="jobdescriptionembedding",
            new_name="job_embeddi_created_66dd89_idx",
            old_name="job_embedding_created_idx",
        ),
        migrations.RenameIndex(
            model_name="modelcosttracking",
            new_name="model_cost__date_2f65ac_idx",
            old_name="cost_tracking_date_model_idx",
        ),
        migrations.RenameIndex(
            model_name="modelcosttracking",
            new_name="model_cost__user_id_5d5785_idx",
            old_name="cost_tracking_user_date_idx",
        ),
        migrations.RenameIndex(
            model_name="modelperformancemetric",
            new_name="model_perfo_model_n_805f74_idx",
            old_name="model_perf_model_task_idx",
        ),
        migrations.RenameIndex(
            model_name="modelperformancemetric",
            new_name="model_perfo_created_5bd507_idx",
            old_name="model_perf_created_idx",
        ),
        migrations.RenameIndex(
            model_name="modelperformancemetric",
            new_name="model_perfo_success_9c8b87_idx",
            old_name="model_perf_success_idx",
        ),
    ]
