# Generated by Django 4.2.24 on 2025-09-25 23:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "llm_services",
            "0002_rename_artifact_chunk_artifact_idx_artifact_ch_artifac_db15f8_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artifactchunk",
            options={"ordering": ["artifact", "chunk_index"]},
        ),
        migrations.AlterModelOptions(
            name="circuitbreakerstate",
            options={"ordering": ["model_name"]},
        ),
        migrations.AlterModelOptions(
            name="enhancedartifact",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="jobdescriptionembedding",
            options={"ordering": ["-last_accessed"]},
        ),
        migrations.AlterModelOptions(
            name="modelcosttracking",
            options={"ordering": ["-date", "model_name"]},
        ),
        migrations.AlterModelOptions(
            name="modelperformancemetric",
            options={"ordering": ["-created_at"]},
        ),
    ]
