# Generated by Django 4.2.24 on 2025-09-30 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0001_initial"),
        ("llm_services", "0003_alter_artifactchunk_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enhancedartifact",
            name="original_artifact_id",
        ),
        migrations.AddField(
            model_name="enhancedartifact",
            name="original_artifact",
            field=models.OneToOneField(
                blank=True,
                help_text="Reference to the original artifact from artifacts app",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enhanced_version",
                to="artifacts.artifact",
            ),
        ),
    ]
