# Generated by Django 4.2.24 on 2025-09-30 08:49

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0001_initial"),
        ("llm_services", "0004_remove_enhancedartifact_original_artifact_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enhancedartifact",
            name="processing_confidence",
            field=models.FloatField(
                default=0.0,
                help_text="Overall confidence in preprocessing quality (0.0-1.0), from ft-005",
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("1.0")),
                ],
            ),
        ),
        migrations.CreateModel(
            name="ExtractedContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("github", "GitHub Repository"),
                            ("pdf", "PDF Document"),
                            ("video", "Video File"),
                            ("audio", "Audio File"),
                            ("web_link", "Web Link"),
                            ("text", "Plain Text"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="Original source URL if applicable",
                        max_length=500,
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        default=dict,
                        help_text="Raw extracted data from source (compressed)",
                    ),
                ),
                (
                    "processed_summary",
                    models.TextField(
                        blank=True,
                        help_text="LLM-generated summary of extracted content",
                    ),
                ),
                ("extraction_success", models.BooleanField(default=True)),
                (
                    "extraction_confidence",
                    models.FloatField(
                        default=0.0,
                        help_text="Confidence score for extraction quality (0.0-1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "processing_duration_ms",
                    models.IntegerField(
                        default=0,
                        help_text="Time taken to process this source in milliseconds",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error details if extraction failed"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "preprocessing_job",
                    models.ForeignKey(
                        help_text="The preprocessing job this extraction belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_contents",
                        to="artifacts.artifactprocessingjob",
                    ),
                ),
            ],
            options={
                "db_table": "extracted_content",
                "ordering": ["preprocessing_job", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["preprocessing_job", "source_type"],
                        name="extracted_c_preproc_a22859_idx",
                    ),
                    models.Index(
                        fields=["extraction_success"],
                        name="extracted_c_extract_c86024_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="extracted_c_created_a59b0b_idx"
                    ),
                ],
            },
        ),
    ]
