# Generated by Django 4.2.24 on 2025-10-01 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("artifacts", "0005_alter_evidence_options_alter_evidence_artifact_and_more"),
        ("llm_services", "0007_rename_table_enhanced_artifacts_to_enhanced_evidence"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artifactchunk",
            options={"ordering": ["enhanced_evidence", "chunk_index"]},
        ),
        migrations.RemoveIndex(
            model_name="artifactchunk",
            name="artifact_ch_artifac_db15f8_idx",
        ),
        migrations.RenameIndex(
            model_name="enhancedevidence",
            new_name="enhanced_ev_user_id_b3989b_idx",
            old_name="enhanced_ar_user_id_08ae58_idx",
        ),
        migrations.RenameIndex(
            model_name="enhancedevidence",
            new_name="enhanced_ev_created_5f5330_idx",
            old_name="enhanced_ar_created_863a56_idx",
        ),
        migrations.RenameIndex(
            model_name="enhancedevidence",
            new_name="enhanced_ev_embeddi_904817_idx",
            old_name="enhanced_ar_embeddi_f97a78_idx",
        ),
        migrations.AlterField(
            model_name="enhancedevidence",
            name="evidence",
            field=models.OneToOneField(
                blank=True,
                help_text="The evidence source this enhancement is based on",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enhanced_version",
                to="artifacts.evidence",
            ),
        ),
        migrations.AlterField(
            model_name="enhancedevidence",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enhanced_evidence",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="artifactchunk",
            index=models.Index(
                fields=["enhanced_evidence", "chunk_index"],
                name="artifact_ch_enhance_8bf7a5_idx",
            ),
        ),
    ]
