# Generated by Django 5.2.7 on 2025-10-08 07:37

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_services", "0010_github_repository_analysis"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="githubrepositoryanalysis",
            new_name="github_repo_evidenc_ffcf5a_idx",
            old_name="github_repo_evidenc_7f0cc3_idx",
        ),
        migrations.RenameIndex(
            model_name="githubrepositoryanalysis",
            new_name="github_repo_detecte_98f6db_idx",
            old_name="github_repo_detecte_74e9e8_idx",
        ),
        migrations.RenameIndex(
            model_name="githubrepositoryanalysis",
            new_name="github_repo_primary_a4ab9c_idx",
            old_name="github_repo_primary_c5e9f2_idx",
        ),
        migrations.RenameIndex(
            model_name="githubrepositoryanalysis",
            new_name="github_repo_analysi_7bdff0_idx",
            old_name="github_repo_analysi_8a7d4f_idx",
        ),
        migrations.RenameIndex(
            model_name="githubrepositoryanalysis",
            new_name="github_repo_created_b3f798_idx",
            old_name="github_repo_created_b5e3d2_idx",
        ),
        migrations.AddField(
            model_name="enhancedevidence",
            name="classification_confidence",
            field=models.FloatField(
                blank=True,
                help_text="Confidence score for document classification (0.0-1.0), from ft-016",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("1.0")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="enhancedevidence",
            name="document_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("resume", "Resume/CV"),
                    ("certificate", "Certificate"),
                    ("research_paper", "Research Paper"),
                    ("project_report", "Project Report"),
                    ("academic_thesis", "Academic Thesis"),
                ],
                help_text="Classified document type for adaptive processing (ft-016)",
                max_length=50,
                null=True,
            ),
        ),
    ]
