# Generated by Django 5.2.7 on 2025-10-17 23:24
# Modified to use SeparateDatabaseAndState since migration 0012
# already dropped these tables and columns using raw SQL.

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_services", "0012_remove_embedding_infrastructure"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Database operations: safe SQL that won't fail if already gone
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DROP TABLE IF EXISTS llm_services_artifactchunk CASCADE;
                        DROP TABLE IF EXISTS llm_services_jobdescriptionembedding CASCADE;
                        DROP INDEX IF EXISTS enhanced_ev_embeddi_904817_idx CASCADE;
                        ALTER TABLE enhanced_evidence DROP COLUMN IF EXISTS content_embedding CASCADE;
                        ALTER TABLE enhanced_evidence DROP COLUMN IF EXISTS summary_embedding CASCADE;
                        ALTER TABLE enhanced_evidence DROP COLUMN IF EXISTS embedding_model CASCADE;
                        ALTER TABLE enhanced_evidence DROP COLUMN IF EXISTS embedding_dimensions CASCADE;
                        ALTER TABLE enhanced_evidence DROP COLUMN IF EXISTS embedding_cost_usd CASCADE;
                        ALTER TABLE enhanced_evidence DROP COLUMN IF EXISTS last_embedding_update CASCADE;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            # State operations: tell Django what changed in the models
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="artifactchunk",
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name="artifactchunk",
                    name="enhanced_evidence",
                ),
                migrations.RemoveField(
                    model_name="jobdescriptionembedding",
                    name="user",
                ),
                migrations.RemoveIndex(
                    model_name="enhancedevidence",
                    name="enhanced_ev_embeddi_904817_idx",
                ),
                migrations.RemoveField(
                    model_name="enhancedevidence",
                    name="content_embedding",
                ),
                migrations.RemoveField(
                    model_name="enhancedevidence",
                    name="embedding_cost_usd",
                ),
                migrations.RemoveField(
                    model_name="enhancedevidence",
                    name="embedding_dimensions",
                ),
                migrations.RemoveField(
                    model_name="enhancedevidence",
                    name="embedding_model",
                ),
                migrations.RemoveField(
                    model_name="enhancedevidence",
                    name="last_embedding_update",
                ),
                migrations.RemoveField(
                    model_name="enhancedevidence",
                    name="summary_embedding",
                ),
                migrations.DeleteModel(
                    name="ArtifactChunk",
                ),
                migrations.DeleteModel(
                    name="JobDescriptionEmbedding",
                ),
            ],
        ),

        # These field alterations are safe to run normally
        migrations.AlterField(
            model_name="enhancedevidence",
            name="classification_confidence",
            field=models.FloatField(
                blank=True,
                help_text="Confidence score for document classification (0.0-1.0)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("1.0")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="enhancedevidence",
            name="processing_confidence",
            field=models.FloatField(
                default=0.0,
                help_text="Overall confidence in preprocessing quality (0.0-1.0)",
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("1.0")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="modelperformancemetric",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("job_parsing", "Job Description Parsing"),
                    ("cv_generation", "CV Content Generation"),
                ],
                max_length=50,
            ),
        ),
    ]
