# Generated by Django 5.2.7 on 2025-11-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_services", "0013_alter_artifactchunk_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enhancedevidence",
            name="accepted",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user has accepted/approved this enhanced evidence",
            ),
        ),
        migrations.AddField(
            model_name="enhancedevidence",
            name="accepted_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when evidence was accepted", null=True
            ),
        ),
    ]
