# Generated by Django 5.2.7 on 2025-11-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_services", "0014_enhancedevidence_accepted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enhancedevidence",
            name="filtered_items_count",
            field=models.IntegerField(
                default=0,
                help_text="Number of items blocked due to low confidence (<0.5) (ft-030)",
            ),
        ),
        migrations.AddField(
            model_name="enhancedevidence",
            name="flagged_items",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Items with 0.5-0.7 confidence that require manual review (ft-030)",
            ),
        ),
    ]
