# Generated by Django 5.2.7 on 2025-11-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llm_services", "0015_enhancedevidence_filtered_items_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enhancedevidence",
            name="filtered_items_count",
        ),
        migrations.RemoveField(
            model_name="enhancedevidence",
            name="flagged_items",
        ),
        migrations.AddField(
            model_name="enhancedevidence",
            name="review_notes",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional notes from user during evidence review",
            ),
        ),
    ]
