# Generated by Django 5.2.7 on 2025-11-07 11:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("llm_services", "0016_remove_enhancedevidence_filtered_items_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="githubrepositoryanalysis",
            name="extracted_content",
        ),
        migrations.DeleteModel(
            name="ExtractedContent",
        ),
    ]
